// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package orcanitrofeed

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *BlockSealMsg) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 7 {
		err = msgp.ArrayError{Wanted: 7, Got: zb0001}
		return
	}
	z.Seq, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "Seq")
		return
	}
	z.BlockNumber, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "BlockNumber")
		return
	}
	z.TxCount, err = dc.ReadUint32()
	if err != nil {
		err = msgp.WrapError(err, "TxCount")
		return
	}
	z.SameTimestampIndex, err = dc.ReadUint32()
	if err != nil {
		err = msgp.WrapError(err, "SameTimestampIndex")
		return
	}
	z.ReceiptCount, err = dc.ReadUint32()
	if err != nil {
		err = msgp.WrapError(err, "ReceiptCount")
		return
	}
	z.L1BlockNumber, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "L1BlockNumber")
		return
	}
	z.L2Timestamp, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "L2Timestamp")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *BlockSealMsg) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 7
	err = en.Append(0x97)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Seq)
	if err != nil {
		err = msgp.WrapError(err, "Seq")
		return
	}
	err = en.WriteUint64(z.BlockNumber)
	if err != nil {
		err = msgp.WrapError(err, "BlockNumber")
		return
	}
	err = en.WriteUint32(z.TxCount)
	if err != nil {
		err = msgp.WrapError(err, "TxCount")
		return
	}
	err = en.WriteUint32(z.SameTimestampIndex)
	if err != nil {
		err = msgp.WrapError(err, "SameTimestampIndex")
		return
	}
	err = en.WriteUint32(z.ReceiptCount)
	if err != nil {
		err = msgp.WrapError(err, "ReceiptCount")
		return
	}
	err = en.WriteUint64(z.L1BlockNumber)
	if err != nil {
		err = msgp.WrapError(err, "L1BlockNumber")
		return
	}
	err = en.WriteUint64(z.L2Timestamp)
	if err != nil {
		err = msgp.WrapError(err, "L2Timestamp")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *BlockSealMsg) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 7
	o = append(o, 0x97)
	o = msgp.AppendUint64(o, z.Seq)
	o = msgp.AppendUint64(o, z.BlockNumber)
	o = msgp.AppendUint32(o, z.TxCount)
	o = msgp.AppendUint32(o, z.SameTimestampIndex)
	o = msgp.AppendUint32(o, z.ReceiptCount)
	o = msgp.AppendUint64(o, z.L1BlockNumber)
	o = msgp.AppendUint64(o, z.L2Timestamp)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *BlockSealMsg) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 7 {
		err = msgp.ArrayError{Wanted: 7, Got: zb0001}
		return
	}
	z.Seq, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Seq")
		return
	}
	z.BlockNumber, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "BlockNumber")
		return
	}
	z.TxCount, bts, err = msgp.ReadUint32Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "TxCount")
		return
	}
	z.SameTimestampIndex, bts, err = msgp.ReadUint32Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "SameTimestampIndex")
		return
	}
	z.ReceiptCount, bts, err = msgp.ReadUint32Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "ReceiptCount")
		return
	}
	z.L1BlockNumber, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "L1BlockNumber")
		return
	}
	z.L2Timestamp, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "L2Timestamp")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *BlockSealMsg) Msgsize() (s int) {
	s = 1 + msgp.Uint64Size + msgp.Uint64Size + msgp.Uint32Size + msgp.Uint32Size + msgp.Uint32Size + msgp.Uint64Size + msgp.Uint64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Hello) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	z.SchemaVersion, err = dc.ReadUint32()
	if err != nil {
		err = msgp.WrapError(err, "SchemaVersion")
		return
	}
	z.Mode, err = dc.ReadString()
	if err != nil {
		err = msgp.WrapError(err, "Mode")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Hello) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 2
	err = en.Append(0x92)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.SchemaVersion)
	if err != nil {
		err = msgp.WrapError(err, "SchemaVersion")
		return
	}
	err = en.WriteString(z.Mode)
	if err != nil {
		err = msgp.WrapError(err, "Mode")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Hello) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 2
	o = append(o, 0x92)
	o = msgp.AppendUint32(o, z.SchemaVersion)
	o = msgp.AppendString(o, z.Mode)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Hello) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	z.SchemaVersion, bts, err = msgp.ReadUint32Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "SchemaVersion")
		return
	}
	z.Mode, bts, err = msgp.ReadStringBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Mode")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Hello) Msgsize() (s int) {
	s = 1 + msgp.Uint32Size + msgp.StringPrefixSize + len(z.Mode)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *InvalidationMsg) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	z.Seq, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "Seq")
		return
	}
	z.BlockNumber, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "BlockNumber")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z InvalidationMsg) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 2
	err = en.Append(0x92)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Seq)
	if err != nil {
		err = msgp.WrapError(err, "Seq")
		return
	}
	err = en.WriteUint64(z.BlockNumber)
	if err != nil {
		err = msgp.WrapError(err, "BlockNumber")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z InvalidationMsg) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 2
	o = append(o, 0x92)
	o = msgp.AppendUint64(o, z.Seq)
	o = msgp.AppendUint64(o, z.BlockNumber)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *InvalidationMsg) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	z.Seq, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Seq")
		return
	}
	z.BlockNumber, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "BlockNumber")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z InvalidationMsg) Msgsize() (s int) {
	s = 1 + msgp.Uint64Size + msgp.Uint64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *LogRecord) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 4 {
		err = msgp.ArrayError{Wanted: 4, Got: zb0001}
		return
	}
	err = dc.ReadExactBytes((z.Address)[:])
	if err != nil {
		err = msgp.WrapError(err, "Address")
		return
	}
	var zb0002 uint32
	zb0002, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err, "Topics")
		return
	}
	if cap(z.Topics) >= int(zb0002) {
		z.Topics = (z.Topics)[:zb0002]
	} else {
		z.Topics = make([][32]byte, zb0002)
	}
	for za0002 := range z.Topics {
		err = dc.ReadExactBytes((z.Topics[za0002])[:])
		if err != nil {
			err = msgp.WrapError(err, "Topics", za0002)
			return
		}
	}
	z.Data, err = dc.ReadBytes(z.Data)
	if err != nil {
		err = msgp.WrapError(err, "Data")
		return
	}
	z.InnerIndex, err = dc.ReadUint16()
	if err != nil {
		err = msgp.WrapError(err, "InnerIndex")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *LogRecord) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 4
	err = en.Append(0x94)
	if err != nil {
		return
	}
	err = en.WriteBytes((z.Address)[:])
	if err != nil {
		err = msgp.WrapError(err, "Address")
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Topics)))
	if err != nil {
		err = msgp.WrapError(err, "Topics")
		return
	}
	for za0002 := range z.Topics {
		err = en.WriteBytes((z.Topics[za0002])[:])
		if err != nil {
			err = msgp.WrapError(err, "Topics", za0002)
			return
		}
	}
	err = en.WriteBytes(z.Data)
	if err != nil {
		err = msgp.WrapError(err, "Data")
		return
	}
	err = en.WriteUint16(z.InnerIndex)
	if err != nil {
		err = msgp.WrapError(err, "InnerIndex")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *LogRecord) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 4
	o = append(o, 0x94)
	o = msgp.AppendBytes(o, (z.Address)[:])
	o = msgp.AppendArrayHeader(o, uint32(len(z.Topics)))
	for za0002 := range z.Topics {
		o = msgp.AppendBytes(o, (z.Topics[za0002])[:])
	}
	o = msgp.AppendBytes(o, z.Data)
	o = msgp.AppendUint16(o, z.InnerIndex)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *LogRecord) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 4 {
		err = msgp.ArrayError{Wanted: 4, Got: zb0001}
		return
	}
	bts, err = msgp.ReadExactBytes(bts, (z.Address)[:])
	if err != nil {
		err = msgp.WrapError(err, "Address")
		return
	}
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Topics")
		return
	}
	if cap(z.Topics) >= int(zb0002) {
		z.Topics = (z.Topics)[:zb0002]
	} else {
		z.Topics = make([][32]byte, zb0002)
	}
	for za0002 := range z.Topics {
		bts, err = msgp.ReadExactBytes(bts, (z.Topics[za0002])[:])
		if err != nil {
			err = msgp.WrapError(err, "Topics", za0002)
			return
		}
	}
	z.Data, bts, err = msgp.ReadBytesBytes(bts, z.Data)
	if err != nil {
		err = msgp.WrapError(err, "Data")
		return
	}
	z.InnerIndex, bts, err = msgp.ReadUint16Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "InnerIndex")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *LogRecord) Msgsize() (s int) {
	s = 1 + msgp.ArrayHeaderSize + (20 * (msgp.ByteSize)) + msgp.ArrayHeaderSize + (len(z.Topics) * (32 * (msgp.ByteSize))) + msgp.BytesPrefixSize + len(z.Data) + msgp.Uint16Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MsgType) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 byte
		zb0001, err = dc.ReadByte()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = MsgType(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z MsgType) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteByte(byte(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z MsgType) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendByte(o, byte(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MsgType) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 byte
		zb0001, bts, err = msgp.ReadByteBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = MsgType(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z MsgType) Msgsize() (s int) {
	s = msgp.ByteSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *RangeDoneMsg) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 3 {
		err = msgp.ArrayError{Wanted: 3, Got: zb0001}
		return
	}
	z.Seq, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "Seq")
		return
	}
	z.StartBlock, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "StartBlock")
		return
	}
	z.EndBlock, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "EndBlock")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z RangeDoneMsg) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 3
	err = en.Append(0x93)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Seq)
	if err != nil {
		err = msgp.WrapError(err, "Seq")
		return
	}
	err = en.WriteUint64(z.StartBlock)
	if err != nil {
		err = msgp.WrapError(err, "StartBlock")
		return
	}
	err = en.WriteUint64(z.EndBlock)
	if err != nil {
		err = msgp.WrapError(err, "EndBlock")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z RangeDoneMsg) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 3
	o = append(o, 0x93)
	o = msgp.AppendUint64(o, z.Seq)
	o = msgp.AppendUint64(o, z.StartBlock)
	o = msgp.AppendUint64(o, z.EndBlock)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *RangeDoneMsg) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 3 {
		err = msgp.ArrayError{Wanted: 3, Got: zb0001}
		return
	}
	z.Seq, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Seq")
		return
	}
	z.StartBlock, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "StartBlock")
		return
	}
	z.EndBlock, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "EndBlock")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z RangeDoneMsg) Msgsize() (s int) {
	s = 1 + msgp.Uint64Size + msgp.Uint64Size + msgp.Uint64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *OrcaNitroReceipt) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 26 {
		err = msgp.ArrayError{Wanted: 26, Got: zb0001}
		return
	}
	z.Seq, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "Seq")
		return
	}
	z.BlockNumber, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "BlockNumber")
		return
	}
	z.TxIndex, err = dc.ReadUint32()
	if err != nil {
		err = msgp.WrapError(err, "TxIndex")
		return
	}
	z.L2Timestamp, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "L2Timestamp")
		return
	}
	z.TxType, err = dc.ReadUint8()
	if err != nil {
		err = msgp.WrapError(err, "TxType")
		return
	}
	err = dc.ReadExactBytes((z.From)[:])
	if err != nil {
		err = msgp.WrapError(err, "From")
		return
	}
	err = dc.ReadExactBytes((z.To)[:])
	if err != nil {
		err = msgp.WrapError(err, "To")
		return
	}
	z.FromAccountKind, err = dc.ReadUint8()
	if err != nil {
		err = msgp.WrapError(err, "FromAccountKind")
		return
	}
	z.ToAccountKind, err = dc.ReadUint8()
	if err != nil {
		err = msgp.WrapError(err, "ToAccountKind")
		return
	}
	err = dc.ReadExactBytes((z.ContractAddress)[:])
	if err != nil {
		err = msgp.WrapError(err, "ContractAddress")
		return
	}
	z.Nonce, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "Nonce")
		return
	}
	z.Gas, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "Gas")
		return
	}
	z.EffectiveGasPrice, err = dc.ReadBytes(z.EffectiveGasPrice)
	if err != nil {
		err = msgp.WrapError(err, "EffectiveGasPrice")
		return
	}
	z.Value, err = dc.ReadBytes(z.Value)
	if err != nil {
		err = msgp.WrapError(err, "Value")
		return
	}
	z.Calldata, err = dc.ReadBytes(z.Calldata)
	if err != nil {
		err = msgp.WrapError(err, "Calldata")
		return
	}
	z.Status, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "Status")
		return
	}
	z.GasUsed, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "GasUsed")
		return
	}
	z.CumulativeGasUsed, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "CumulativeGasUsed")
		return
	}
	z.GasUsedForL1, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "GasUsedForL1")
		return
	}
	z.L1BlockNumber, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "L1BlockNumber")
		return
	}
	var zb0002 uint32
	zb0002, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err, "Logs")
		return
	}
	if cap(z.Logs) >= int(zb0002) {
		z.Logs = (z.Logs)[:zb0002]
	} else {
		z.Logs = make([]LogRecord, zb0002)
	}
	for za0004 := range z.Logs {
		err = z.Logs[za0004].DecodeMsg(dc)
		if err != nil {
			err = msgp.WrapError(err, "Logs", za0004)
			return
		}
	}
	var zb0003 uint32
	zb0003, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err, "Transfers")
		return
	}
	if cap(z.Transfers) >= int(zb0003) {
		z.Transfers = (z.Transfers)[:zb0003]
	} else {
		z.Transfers = make([]TransferRecord, zb0003)
	}
	for za0005 := range z.Transfers {
		err = z.Transfers[za0005].DecodeMsg(dc)
		if err != nil {
			err = msgp.WrapError(err, "Transfers", za0005)
			return
		}
	}
	var zb0004 uint32
	zb0004, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err, "Calls")
		return
	}
	if cap(z.Calls) >= int(zb0004) {
		z.Calls = (z.Calls)[:zb0004]
	} else {
		z.Calls = make([]WhitelistedCallRecord, zb0004)
	}
	for za0006 := range z.Calls {
		err = z.Calls[za0006].DecodeMsg(dc)
		if err != nil {
			err = msgp.WrapError(err, "Calls", za0006)
			return
		}
	}
	z.EmittedAtNs, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "EmittedAtNs")
		return
	}
	z.SameTimestampIndex, err = dc.ReadUint32()
	if err != nil {
		err = msgp.WrapError(err, "SameTimestampIndex")
		return
	}
	z.RevertOutput, err = dc.ReadBytes(z.RevertOutput)
	if err != nil {
		err = msgp.WrapError(err, "RevertOutput")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *OrcaNitroReceipt) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 26
	err = en.Append(0xdc, 0x0, 0x1a)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Seq)
	if err != nil {
		err = msgp.WrapError(err, "Seq")
		return
	}
	err = en.WriteUint64(z.BlockNumber)
	if err != nil {
		err = msgp.WrapError(err, "BlockNumber")
		return
	}
	err = en.WriteUint32(z.TxIndex)
	if err != nil {
		err = msgp.WrapError(err, "TxIndex")
		return
	}
	err = en.WriteUint64(z.L2Timestamp)
	if err != nil {
		err = msgp.WrapError(err, "L2Timestamp")
		return
	}
	err = en.WriteUint8(z.TxType)
	if err != nil {
		err = msgp.WrapError(err, "TxType")
		return
	}
	err = en.WriteBytes((z.From)[:])
	if err != nil {
		err = msgp.WrapError(err, "From")
		return
	}
	err = en.WriteBytes((z.To)[:])
	if err != nil {
		err = msgp.WrapError(err, "To")
		return
	}
	err = en.WriteUint8(z.FromAccountKind)
	if err != nil {
		err = msgp.WrapError(err, "FromAccountKind")
		return
	}
	err = en.WriteUint8(z.ToAccountKind)
	if err != nil {
		err = msgp.WrapError(err, "ToAccountKind")
		return
	}
	err = en.WriteBytes((z.ContractAddress)[:])
	if err != nil {
		err = msgp.WrapError(err, "ContractAddress")
		return
	}
	err = en.WriteUint64(z.Nonce)
	if err != nil {
		err = msgp.WrapError(err, "Nonce")
		return
	}
	err = en.WriteUint64(z.Gas)
	if err != nil {
		err = msgp.WrapError(err, "Gas")
		return
	}
	err = en.WriteBytes(z.EffectiveGasPrice)
	if err != nil {
		err = msgp.WrapError(err, "EffectiveGasPrice")
		return
	}
	err = en.WriteBytes(z.Value)
	if err != nil {
		err = msgp.WrapError(err, "Value")
		return
	}
	err = en.WriteBytes(z.Calldata)
	if err != nil {
		err = msgp.WrapError(err, "Calldata")
		return
	}
	err = en.WriteUint64(z.Status)
	if err != nil {
		err = msgp.WrapError(err, "Status")
		return
	}
	err = en.WriteUint64(z.GasUsed)
	if err != nil {
		err = msgp.WrapError(err, "GasUsed")
		return
	}
	err = en.WriteUint64(z.CumulativeGasUsed)
	if err != nil {
		err = msgp.WrapError(err, "CumulativeGasUsed")
		return
	}
	err = en.WriteUint64(z.GasUsedForL1)
	if err != nil {
		err = msgp.WrapError(err, "GasUsedForL1")
		return
	}
	err = en.WriteUint64(z.L1BlockNumber)
	if err != nil {
		err = msgp.WrapError(err, "L1BlockNumber")
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Logs)))
	if err != nil {
		err = msgp.WrapError(err, "Logs")
		return
	}
	for za0004 := range z.Logs {
		err = z.Logs[za0004].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Logs", za0004)
			return
		}
	}
	err = en.WriteArrayHeader(uint32(len(z.Transfers)))
	if err != nil {
		err = msgp.WrapError(err, "Transfers")
		return
	}
	for za0005 := range z.Transfers {
		err = z.Transfers[za0005].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Transfers", za0005)
			return
		}
	}
	err = en.WriteArrayHeader(uint32(len(z.Calls)))
	if err != nil {
		err = msgp.WrapError(err, "Calls")
		return
	}
	for za0006 := range z.Calls {
		err = z.Calls[za0006].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Calls", za0006)
			return
		}
	}
	err = en.WriteUint64(z.EmittedAtNs)
	if err != nil {
		err = msgp.WrapError(err, "EmittedAtNs")
		return
	}
	err = en.WriteUint32(z.SameTimestampIndex)
	if err != nil {
		err = msgp.WrapError(err, "SameTimestampIndex")
		return
	}
	err = en.WriteBytes(z.RevertOutput)
	if err != nil {
		err = msgp.WrapError(err, "RevertOutput")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *OrcaNitroReceipt) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 26
	o = append(o, 0xdc, 0x0, 0x1a)
	o = msgp.AppendUint64(o, z.Seq)
	o = msgp.AppendUint64(o, z.BlockNumber)
	o = msgp.AppendUint32(o, z.TxIndex)
	o = msgp.AppendUint64(o, z.L2Timestamp)
	o = msgp.AppendUint8(o, z.TxType)
	o = msgp.AppendBytes(o, (z.From)[:])
	o = msgp.AppendBytes(o, (z.To)[:])
	o = msgp.AppendUint8(o, z.FromAccountKind)
	o = msgp.AppendUint8(o, z.ToAccountKind)
	o = msgp.AppendBytes(o, (z.ContractAddress)[:])
	o = msgp.AppendUint64(o, z.Nonce)
	o = msgp.AppendUint64(o, z.Gas)
	o = msgp.AppendBytes(o, z.EffectiveGasPrice)
	o = msgp.AppendBytes(o, z.Value)
	o = msgp.AppendBytes(o, z.Calldata)
	o = msgp.AppendUint64(o, z.Status)
	o = msgp.AppendUint64(o, z.GasUsed)
	o = msgp.AppendUint64(o, z.CumulativeGasUsed)
	o = msgp.AppendUint64(o, z.GasUsedForL1)
	o = msgp.AppendUint64(o, z.L1BlockNumber)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Logs)))
	for za0004 := range z.Logs {
		o, err = z.Logs[za0004].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Logs", za0004)
			return
		}
	}
	o = msgp.AppendArrayHeader(o, uint32(len(z.Transfers)))
	for za0005 := range z.Transfers {
		o, err = z.Transfers[za0005].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Transfers", za0005)
			return
		}
	}
	o = msgp.AppendArrayHeader(o, uint32(len(z.Calls)))
	for za0006 := range z.Calls {
		o, err = z.Calls[za0006].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Calls", za0006)
			return
		}
	}
	o = msgp.AppendUint64(o, z.EmittedAtNs)
	o = msgp.AppendUint32(o, z.SameTimestampIndex)
	o = msgp.AppendBytes(o, z.RevertOutput)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *OrcaNitroReceipt) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 26 {
		err = msgp.ArrayError{Wanted: 26, Got: zb0001}
		return
	}
	z.Seq, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Seq")
		return
	}
	z.BlockNumber, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "BlockNumber")
		return
	}
	z.TxIndex, bts, err = msgp.ReadUint32Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "TxIndex")
		return
	}
	z.L2Timestamp, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "L2Timestamp")
		return
	}
	z.TxType, bts, err = msgp.ReadUint8Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "TxType")
		return
	}
	bts, err = msgp.ReadExactBytes(bts, (z.From)[:])
	if err != nil {
		err = msgp.WrapError(err, "From")
		return
	}
	bts, err = msgp.ReadExactBytes(bts, (z.To)[:])
	if err != nil {
		err = msgp.WrapError(err, "To")
		return
	}
	z.FromAccountKind, bts, err = msgp.ReadUint8Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "FromAccountKind")
		return
	}
	z.ToAccountKind, bts, err = msgp.ReadUint8Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "ToAccountKind")
		return
	}
	bts, err = msgp.ReadExactBytes(bts, (z.ContractAddress)[:])
	if err != nil {
		err = msgp.WrapError(err, "ContractAddress")
		return
	}
	z.Nonce, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Nonce")
		return
	}
	z.Gas, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Gas")
		return
	}
	z.EffectiveGasPrice, bts, err = msgp.ReadBytesBytes(bts, z.EffectiveGasPrice)
	if err != nil {
		err = msgp.WrapError(err, "EffectiveGasPrice")
		return
	}
	z.Value, bts, err = msgp.ReadBytesBytes(bts, z.Value)
	if err != nil {
		err = msgp.WrapError(err, "Value")
		return
	}
	z.Calldata, bts, err = msgp.ReadBytesBytes(bts, z.Calldata)
	if err != nil {
		err = msgp.WrapError(err, "Calldata")
		return
	}
	z.Status, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Status")
		return
	}
	z.GasUsed, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "GasUsed")
		return
	}
	z.CumulativeGasUsed, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "CumulativeGasUsed")
		return
	}
	z.GasUsedForL1, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "GasUsedForL1")
		return
	}
	z.L1BlockNumber, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "L1BlockNumber")
		return
	}
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Logs")
		return
	}
	if cap(z.Logs) >= int(zb0002) {
		z.Logs = (z.Logs)[:zb0002]
	} else {
		z.Logs = make([]LogRecord, zb0002)
	}
	for za0004 := range z.Logs {
		bts, err = z.Logs[za0004].UnmarshalMsg(bts)
		if err != nil {
			err = msgp.WrapError(err, "Logs", za0004)
			return
		}
	}
	var zb0003 uint32
	zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Transfers")
		return
	}
	if cap(z.Transfers) >= int(zb0003) {
		z.Transfers = (z.Transfers)[:zb0003]
	} else {
		z.Transfers = make([]TransferRecord, zb0003)
	}
	for za0005 := range z.Transfers {
		bts, err = z.Transfers[za0005].UnmarshalMsg(bts)
		if err != nil {
			err = msgp.WrapError(err, "Transfers", za0005)
			return
		}
	}
	var zb0004 uint32
	zb0004, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Calls")
		return
	}
	if cap(z.Calls) >= int(zb0004) {
		z.Calls = (z.Calls)[:zb0004]
	} else {
		z.Calls = make([]WhitelistedCallRecord, zb0004)
	}
	for za0006 := range z.Calls {
		bts, err = z.Calls[za0006].UnmarshalMsg(bts)
		if err != nil {
			err = msgp.WrapError(err, "Calls", za0006)
			return
		}
	}
	z.EmittedAtNs, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "EmittedAtNs")
		return
	}
	z.SameTimestampIndex, bts, err = msgp.ReadUint32Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "SameTimestampIndex")
		return
	}
	z.RevertOutput, bts, err = msgp.ReadBytesBytes(bts, z.RevertOutput)
	if err != nil {
		err = msgp.WrapError(err, "RevertOutput")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *OrcaNitroReceipt) Msgsize() (s int) {
	s = 3 + msgp.Uint64Size + msgp.Uint64Size + msgp.Uint32Size + msgp.Uint64Size + msgp.Uint8Size + msgp.ArrayHeaderSize + (20 * (msgp.ByteSize)) + msgp.ArrayHeaderSize + (20 * (msgp.ByteSize)) + msgp.Uint8Size + msgp.Uint8Size + msgp.ArrayHeaderSize + (20 * (msgp.ByteSize)) + msgp.Uint64Size + msgp.Uint64Size + msgp.BytesPrefixSize + len(z.EffectiveGasPrice) + msgp.BytesPrefixSize + len(z.Value) + msgp.BytesPrefixSize + len(z.Calldata) + msgp.Uint64Size + msgp.Uint64Size + msgp.Uint64Size + msgp.Uint64Size + msgp.Uint64Size + msgp.ArrayHeaderSize
	for za0004 := range z.Logs {
		s += z.Logs[za0004].Msgsize()
	}
	s += msgp.ArrayHeaderSize
	for za0005 := range z.Transfers {
		s += z.Transfers[za0005].Msgsize()
	}
	s += msgp.ArrayHeaderSize
	for za0006 := range z.Calls {
		s += z.Calls[za0006].Msgsize()
	}
	s += msgp.Uint64Size + msgp.Uint32Size + msgp.BytesPrefixSize + len(z.RevertOutput)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *TransferRecord) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 9 {
		err = msgp.ArrayError{Wanted: 9, Got: zb0001}
		return
	}
	z.Reason, err = dc.ReadUint8()
	if err != nil {
		err = msgp.WrapError(err, "Reason")
		return
	}
	err = dc.ReadExactBytes((z.From)[:])
	if err != nil {
		err = msgp.WrapError(err, "From")
		return
	}
	err = dc.ReadExactBytes((z.To)[:])
	if err != nil {
		err = msgp.WrapError(err, "To")
		return
	}
	z.Value, err = dc.ReadBytes(z.Value)
	if err != nil {
		err = msgp.WrapError(err, "Value")
		return
	}
	z.PostBalanceFrom, err = dc.ReadBytes(z.PostBalanceFrom)
	if err != nil {
		err = msgp.WrapError(err, "PostBalanceFrom")
		return
	}
	z.PostBalanceTo, err = dc.ReadBytes(z.PostBalanceTo)
	if err != nil {
		err = msgp.WrapError(err, "PostBalanceTo")
		return
	}
	z.Depth, err = dc.ReadUint16()
	if err != nil {
		err = msgp.WrapError(err, "Depth")
		return
	}
	z.Reverted, err = dc.ReadBool()
	if err != nil {
		err = msgp.WrapError(err, "Reverted")
		return
	}
	z.InnerIndex, err = dc.ReadUint16()
	if err != nil {
		err = msgp.WrapError(err, "InnerIndex")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *TransferRecord) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 9
	err = en.Append(0x99)
	if err != nil {
		return
	}
	err = en.WriteUint8(z.Reason)
	if err != nil {
		err = msgp.WrapError(err, "Reason")
		return
	}
	err = en.WriteBytes((z.From)[:])
	if err != nil {
		err = msgp.WrapError(err, "From")
		return
	}
	err = en.WriteBytes((z.To)[:])
	if err != nil {
		err = msgp.WrapError(err, "To")
		return
	}
	err = en.WriteBytes(z.Value)
	if err != nil {
		err = msgp.WrapError(err, "Value")
		return
	}
	err = en.WriteBytes(z.PostBalanceFrom)
	if err != nil {
		err = msgp.WrapError(err, "PostBalanceFrom")
		return
	}
	err = en.WriteBytes(z.PostBalanceTo)
	if err != nil {
		err = msgp.WrapError(err, "PostBalanceTo")
		return
	}
	err = en.WriteUint16(z.Depth)
	if err != nil {
		err = msgp.WrapError(err, "Depth")
		return
	}
	err = en.WriteBool(z.Reverted)
	if err != nil {
		err = msgp.WrapError(err, "Reverted")
		return
	}
	err = en.WriteUint16(z.InnerIndex)
	if err != nil {
		err = msgp.WrapError(err, "InnerIndex")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *TransferRecord) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 9
	o = append(o, 0x99)
	o = msgp.AppendUint8(o, z.Reason)
	o = msgp.AppendBytes(o, (z.From)[:])
	o = msgp.AppendBytes(o, (z.To)[:])
	o = msgp.AppendBytes(o, z.Value)
	o = msgp.AppendBytes(o, z.PostBalanceFrom)
	o = msgp.AppendBytes(o, z.PostBalanceTo)
	o = msgp.AppendUint16(o, z.Depth)
	o = msgp.AppendBool(o, z.Reverted)
	o = msgp.AppendUint16(o, z.InnerIndex)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *TransferRecord) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 9 {
		err = msgp.ArrayError{Wanted: 9, Got: zb0001}
		return
	}
	z.Reason, bts, err = msgp.ReadUint8Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Reason")
		return
	}
	bts, err = msgp.ReadExactBytes(bts, (z.From)[:])
	if err != nil {
		err = msgp.WrapError(err, "From")
		return
	}
	bts, err = msgp.ReadExactBytes(bts, (z.To)[:])
	if err != nil {
		err = msgp.WrapError(err, "To")
		return
	}
	z.Value, bts, err = msgp.ReadBytesBytes(bts, z.Value)
	if err != nil {
		err = msgp.WrapError(err, "Value")
		return
	}
	z.PostBalanceFrom, bts, err = msgp.ReadBytesBytes(bts, z.PostBalanceFrom)
	if err != nil {
		err = msgp.WrapError(err, "PostBalanceFrom")
		return
	}
	z.PostBalanceTo, bts, err = msgp.ReadBytesBytes(bts, z.PostBalanceTo)
	if err != nil {
		err = msgp.WrapError(err, "PostBalanceTo")
		return
	}
	z.Depth, bts, err = msgp.ReadUint16Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Depth")
		return
	}
	z.Reverted, bts, err = msgp.ReadBoolBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Reverted")
		return
	}
	z.InnerIndex, bts, err = msgp.ReadUint16Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "InnerIndex")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *TransferRecord) Msgsize() (s int) {
	s = 1 + msgp.Uint8Size + msgp.ArrayHeaderSize + (20 * (msgp.ByteSize)) + msgp.ArrayHeaderSize + (20 * (msgp.ByteSize)) + msgp.BytesPrefixSize + len(z.Value) + msgp.BytesPrefixSize + len(z.PostBalanceFrom) + msgp.BytesPrefixSize + len(z.PostBalanceTo) + msgp.Uint16Size + msgp.BoolSize + msgp.Uint16Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *WhitelistedCallRecord) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 9 {
		err = msgp.ArrayError{Wanted: 9, Got: zb0001}
		return
	}
	err = dc.ReadExactBytes((z.To)[:])
	if err != nil {
		err = msgp.WrapError(err, "To")
		return
	}
	err = dc.ReadExactBytes((z.Selector)[:])
	if err != nil {
		err = msgp.WrapError(err, "Selector")
		return
	}
	z.Input, err = dc.ReadBytes(z.Input)
	if err != nil {
		err = msgp.WrapError(err, "Input")
		return
	}
	z.Value, err = dc.ReadBytes(z.Value)
	if err != nil {
		err = msgp.WrapError(err, "Value")
		return
	}
	z.Depth, err = dc.ReadUint16()
	if err != nil {
		err = msgp.WrapError(err, "Depth")
		return
	}
	z.Reverted, err = dc.ReadBool()
	if err != nil {
		err = msgp.WrapError(err, "Reverted")
		return
	}
	z.InnerIndex, err = dc.ReadUint16()
	if err != nil {
		err = msgp.WrapError(err, "InnerIndex")
		return
	}
	z.RevertReason, err = dc.ReadBytes(z.RevertReason)
	if err != nil {
		err = msgp.WrapError(err, "RevertReason")
		return
	}
	z.ExitInnerIndex, err = dc.ReadUint16()
	if err != nil {
		err = msgp.WrapError(err, "ExitInnerIndex")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *WhitelistedCallRecord) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 9
	err = en.Append(0x99)
	if err != nil {
		return
	}
	err = en.WriteBytes((z.To)[:])
	if err != nil {
		err = msgp.WrapError(err, "To")
		return
	}
	err = en.WriteBytes((z.Selector)[:])
	if err != nil {
		err = msgp.WrapError(err, "Selector")
		return
	}
	err = en.WriteBytes(z.Input)
	if err != nil {
		err = msgp.WrapError(err, "Input")
		return
	}
	err = en.WriteBytes(z.Value)
	if err != nil {
		err = msgp.WrapError(err, "Value")
		return
	}
	err = en.WriteUint16(z.Depth)
	if err != nil {
		err = msgp.WrapError(err, "Depth")
		return
	}
	err = en.WriteBool(z.Reverted)
	if err != nil {
		err = msgp.WrapError(err, "Reverted")
		return
	}
	err = en.WriteUint16(z.InnerIndex)
	if err != nil {
		err = msgp.WrapError(err, "InnerIndex")
		return
	}
	err = en.WriteBytes(z.RevertReason)
	if err != nil {
		err = msgp.WrapError(err, "RevertReason")
		return
	}
	err = en.WriteUint16(z.ExitInnerIndex)
	if err != nil {
		err = msgp.WrapError(err, "ExitInnerIndex")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *WhitelistedCallRecord) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 9
	o = append(o, 0x99)
	o = msgp.AppendBytes(o, (z.To)[:])
	o = msgp.AppendBytes(o, (z.Selector)[:])
	o = msgp.AppendBytes(o, z.Input)
	o = msgp.AppendBytes(o, z.Value)
	o = msgp.AppendUint16(o, z.Depth)
	o = msgp.AppendBool(o, z.Reverted)
	o = msgp.AppendUint16(o, z.InnerIndex)
	o = msgp.AppendBytes(o, z.RevertReason)
	o = msgp.AppendUint16(o, z.ExitInnerIndex)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *WhitelistedCallRecord) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 9 {
		err = msgp.ArrayError{Wanted: 9, Got: zb0001}
		return
	}
	bts, err = msgp.ReadExactBytes(bts, (z.To)[:])
	if err != nil {
		err = msgp.WrapError(err, "To")
		return
	}
	bts, err = msgp.ReadExactBytes(bts, (z.Selector)[:])
	if err != nil {
		err = msgp.WrapError(err, "Selector")
		return
	}
	z.Input, bts, err = msgp.ReadBytesBytes(bts, z.Input)
	if err != nil {
		err = msgp.WrapError(err, "Input")
		return
	}
	z.Value, bts, err = msgp.ReadBytesBytes(bts, z.Value)
	if err != nil {
		err = msgp.WrapError(err, "Value")
		return
	}
	z.Depth, bts, err = msgp.ReadUint16Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Depth")
		return
	}
	z.Reverted, bts, err = msgp.ReadBoolBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Reverted")
		return
	}
	z.InnerIndex, bts, err = msgp.ReadUint16Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "InnerIndex")
		return
	}
	z.RevertReason, bts, err = msgp.ReadBytesBytes(bts, z.RevertReason)
	if err != nil {
		err = msgp.WrapError(err, "RevertReason")
		return
	}
	z.ExitInnerIndex, bts, err = msgp.ReadUint16Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "ExitInnerIndex")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *WhitelistedCallRecord) Msgsize() (s int) {
	s = 1 + msgp.ArrayHeaderSize + (20 * (msgp.ByteSize)) + msgp.ArrayHeaderSize + (4 * (msgp.ByteSize)) + msgp.BytesPrefixSize + len(z.Input) + msgp.BytesPrefixSize + len(z.Value) + msgp.Uint16Size + msgp.BoolSize + msgp.Uint16Size + msgp.BytesPrefixSize + len(z.RevertReason) + msgp.Uint16Size
	return
}
